### ISSUE TITLE
Going online task list

### ISSUE THREAD

**Issue by bacloud14** [bacloud14/WeatherVenue#21]
Finish development

- [x] Finish current issues which are:
- [x] Fix weather alerts panel, this one is a panel on Google map that is floating unpredictably on window resize.
- [x] Other minor issues.
- [x] Accessibility: this one is 50% implemented, it listens to user but does not tell forecasts yet.
- [x] Robots.txt and sitemap.xml

Deployment

- [x] Choose Heroku Redis as a store and re-implement Redit queries
- [x] Configure environment variables
- [x] Add a domain and link it in domain provider to Heroku DSN
- [ ] Git flow from now on: Master, Develop, Features branches. Only -hotfixes and develop are based on master directly
- [x] Google search console
